---
# Source: F5Demo/templates/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5demo-as3-configmap
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.1.0",
        "id": "f5demo",
        "label": "CIS AS3 Example",
        "remark": "Example of using CIS",
       "Common": {
          "class": "Tenant",
          "Shared": {
            "class": "Application",
            "template": "shared",
            "XFF_HTTP_Profile": {
              "class": "HTTP_Profile",
                "xForwardedFor": true
               }       
                

       }
       },
        "AS3": {
          "class": "Tenant",
          "MyApps": {
             "class": "Application",
             "template": "generic",
             "frontend": {
                "class": "Service_TCP",
                "virtualAddresses": ["10.1.10.81"
                ],
               "remark":"frontend: f5demo.tcp.v1",
               
               "virtualPort": 80,
                "pool": "frontend_pool"
             },
             "frontend_pool": {
                "class": "Pool",
                "monitors": [
                   "tcp"
                ],
                "members": [{
                   "servicePort": 80,
                   "serverAddresses": []
                }]
             },
             "website": {
                "class": "Service_HTTP",
                "virtualAddresses": ["10.1.10.80"
                ],
               
               
               "remark":"website: f5demo.http.v1",
               "pool": "website_pool",
               "profileHTTP":{"use": "/Common/Shared/XFF_HTTP_Profile"}
             },
             "website_pool": {
                "class": "Pool",
                "monitors": [
                   "http"
                ],
                "members": [{
                   "servicePort": 80,
                   "serverAddresses": [
                   ]
                }]
             },
             "websitetls": {
                "class": "Service_HTTPS",
                "virtualAddresses": ["10.1.10.80"
                ],
               
               "remark":"websitetls: f5demo.https.v1",
               "pool": "websitetls_pool",
               "profileHTTP":{"use": "/Common/Shared/XFF_HTTP_Profile"},
               "redirect80": false,            
               "serverTLS": {"bigip":"/Common/_wildcard_.f5demo.com_clientssl"},
               "clientTLS": {"bigip":"/Common/serverssl"}
             },
             "websitetls_pool": {
                "class": "Pool",
                "monitors": [
                   "https"
                ],
                "members": [{
                   "servicePort": 443,
                   "serverAddresses": [
                   ]
                }]
             }
       }
       }
    }
    }

