apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-blue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: node-blue
    spec:
      containers:
      - image: "f5devcentral/f5-demo-httpd"
        env:
        - name: F5DEMO_APP
          value: "website"
        - name: F5DEMO_NODENAME
          value: "Node Blue (No SSL)"
        - name: F5DEMO_NODENAME_SSL
          value: "Node Blue (SSL)"
        - name: F5DEMO_COLOR
          value: "9999FF"
        - name: F5DEMO_COLOR_SSL
          value: "0000FF"
        imagePullPolicy: IfNotPresent
        name: node-blue
        ports:
        - containerPort: 80
        - containerPort: 443
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: node-blue
  labels:
    run: node-blue
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  - port: 443
    protocol: TCP
    targetPort: 443
    name: https
  type: NodePort
  selector:
    run: node-blue

---
apiVersion: v1
kind: Service
metadata:
  name: node-blue-tls
  labels:
    run: node-blue-tls
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
    name: https
  type: NodePort
  selector:
    run: node-blue
