# Source: f5-bigip-ctlr/templates/f5-bigip-ctlr-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: bigip1-f5-bigip-ctlr
  labels:
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.6
    release: bigip1
    heritage: Tiller
rules:
- apiGroups:
  - ""
  - "extensions"
  resources:
  - nodes
  - services
  - endpoints
  - namespaces
  - ingresses
  - secrets
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - "extensions"
  resources:
  - configmaps
  - events
  - ingresses/status
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - patch
---
# Source: f5-bigip-ctlr/templates/f5-bigip-ctlr-clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: bigip1-f5-bigip-ctlr
  labels:
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.6
    release: bigip1
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bigip1-f5-bigip-ctlr
subjects:
- kind: ServiceAccount
  name: bigip1-f5-bigip-ctlr
  namespace: "kube-system"

