---
# Source: F5Demo/templates/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5demo-as3-configmap
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.1.0",
        "id": "f5demo",
        "label": "CIS AS3 Example",
        "remark": "Example of using CIS ConfigMap",
        "ConfigMap": {
          "class": "Tenant",
          "MyApps": {
             "class": "Application",
             "template": "generic",
             "frontend": {
                "class": "Service_TCP",
                "virtualAddresses": ["10.1.10.101"],
               "remark":"frontend: f5demo.tcp.v1",
               "persistenceMethods":[],
               "virtualPort": 80,
                "pool": "frontend2_pool"
             },
             "frontend2_pool": {
                "class": "Pool",
                "monitors": [ "tcp" ],
                "members": [{
                   "servicePort": 8080,
                   "serverAddresses": [],
                   "shareNodes": true
                }]
             },
             "ingress": {
                "class": "Service_TCP",
                "virtualAddresses": ["10.1.10.102"
                ],
               
               "virtualPort": 80,
               "remark":"ingress: f5demo.proxyprotocol.tcp.v1",
               "pool": "ingress_pool",
               "iRules": ["Proxy_Protocol_Send"]
             },
             "ingress_pool": {
                "class": "Pool",
                "monitors": [
                   "tcp"
                ],
                "members": [{
                   "servicePort": 80,
                   "serverAddresses": [],
                   "shareNodes": true		   
                }]
             },
             "ingresstls": {
                "class": "Service_TCP",
                "virtualAddresses": ["10.1.10.102"
                ],
               
               "virtualPort": 443,
               "remark":"ingresstls: f5demo.proxyprotocol.tcp.v1",
               "pool": "ingresstls_pool",
               "iRules": ["Proxy_Protocol_Send"]
             },
             "ingresstls_pool": {
                "class": "Pool",
                "monitors": [
                   "tcp"
                ],
                "members": [{
                   "servicePort": 80,
                   "serverAddresses": [],
                   "shareNodes": true		   
                }]
             },
             "nginxplusapi": {
                "class": "Service_TCP",
                "virtualAddresses": ["10.1.10.102"],
               "remark":"nginxplusapi: f5demo.tcp.v1",
               
               "virtualPort": 9090,
                "pool": "nginxplusapi_pool"
             },
             "nginxplusapi_pool": {
                "class": "Pool",
                "monitors": [ "tcp" ],
                "members": [{
                   "servicePort": 80,
                   "serverAddresses": [],
                   "shareNodes": true		   
                }]
             },	     
            "XFF_HTTP_Profile": {
              "class": "HTTP_Profile",
                "xForwardedFor": true
             },                       
                "Proxy_Protocol_Send": {
                  "class":"iRule",
                  "iRule": {"base64": "d2hlbiBTRVJWRVJfQ09OTkVDVEVEIHsKICAgICAgVENQOjpyZXNwb25kICJQUk9YWSBUQ1BbSVA6OnZlcnNpb25dIFtJUDo6Y2xpZW50X2FkZHJdIFtjbGllbnRzaWRlIHtJUDo6bG9jYWxfYWRkcn1dIFtUQ1A6OmNsaWVudF9wb3J0XSBbY2xpZW50c2lkZSB7VENQOjpsb2NhbF9wb3J0fV1cclxuIgp9Cg=="}
                }	     
       }
       }
    }
    }
    

