kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-override
  namespace: default
  labels:
    f5type: virtual-server
    overrideAS3: "true"
data:
  template: |
    {
        "declaration": {
            "ocp_AS3": {
                "Shared": {
                    "ose_vserver": {
                        "securityLogProfiles": [
                            {
                                "bigip": "/Common/Log all requests"
                            }
                        ],
                        "policyWAF": {
                            "bigip": "/Common/linux-low"
                        },
                        "persistenceMethods": [],
                        "profileMultiplex": {
                            "bigip": "/Common/oneconnect"
                        },
                        "profileHTTP":{"use": "XFF_HTTP_Profile"}
                    },
                    "XFF_HTTP_Profile": {
                        "class": "HTTP_Profile",
                        "xForwardedFor": true
                    }		    
                }
            }
        }
    }
