apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blue-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/location-snippets: |
      add_header X-nginx-ingress $hostname;
    appprotect.f5.com/app-protect-policy: "nginx-ingress/basic-block"
    appprotect.f5.com/app-protect-enable: "True"
    appprotect.f5.com/app-protect-security-log-enable: "True"
    appprotect.f5.com/app-protect-security-log: "nginx-ingress/logconf"
    appprotect.f5.com/app-protect-security-log-destination: "syslog:server=10.1.1.4:514"
spec:
  tls:
    - hosts:
      - blue.ingress.dc1.example.com
      # This assumes tls-secret exists and the SSL 
      # certificate contains a CN for foo.bar.com
      secretName: tls-secret
  rules:
  - host: blue.ingress.dc1.example.com
    http:
      paths:
      - backend:
          serviceName: node-blue
          servicePort: 80
