---
# Source: f5-bigip-ctlr/templates/f5-bigip-ctlr-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chen-f5-bigip-ctlr
  namespace: kube-system
  labels:
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.7
    release: chen
    heritage: Helm
---
# Source: f5-bigip-ctlr/templates/f5-bigip-ctlr-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: chen-f5-bigip-ctlr
  labels:
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.7
    release: chen
    heritage: Helm
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
      - apps
      - extensions
      - route.openshift.io
    resources:
      - nodes
      - services
      - endpoints
      - namespaces
      - ingresses
      - secrets
      - pods
      - routes
  - verbs:
      - get
      - list
      - watch
      - update
      - create
      - patch
    apiGroups:
      - ''
      - apps
      - extensions
      - route.openshift.io
    resources:
      - configmaps
      - events
      - ingresses/status
      - routes/status
---
# Source: f5-bigip-ctlr/templates/f5-bigip-ctlr-clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: chen-f5-bigip-ctlr
  namespace: kube-system
  labels:
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.7
    release: chen
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chen-f5-bigip-ctlr
subjects:
- kind: ServiceAccount
  name: chen-f5-bigip-ctlr
  namespace: kube-system
---
# Source: f5-bigip-ctlr/templates/f5-bigip-ctlr-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chen-f5-bigip-ctlr
  namespace: kube-system
  labels:
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.7
    release: chen
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5-bigip-ctlr
  template:
    metadata:
      labels:
        app: f5-bigip-ctlr
        release: chen
    spec:
      serviceAccountName: chen-f5-bigip-ctlr
      containers:
      - name: f5-bigip-ctlr
        image: "f5networks/k8s-bigip-ctlr:2.0.0"
        env:
          - name: BIGIP_USERNAME
            valueFrom:
              secretKeyRef:
                name: bigip-login
                key: username
          - name: BIGIP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bigip-login
                key: password

        imagePullPolicy: Always
        command:
        - /app/bin/k8s-bigip-ctlr
        args:
        - --bigip-username
        - $(BIGIP_USERNAME)
        - --bigip-password
        - $(BIGIP_PASSWORD)

        - --agent
        - "as3"
        - --bigip-partition
        - "ocp"
        - --bigip-url
        - "192.168.131.240"
        - --insecure
        - "true"
        - --log-as3-response
        - "true"
        - --log-level
        - "INFO"
        - --manage-routes
        - "true"
        - --namespace
        - "default"
        - --openshift-sdn-name
        - "/Common/openshift_vxlan"
        - --pool-member-type
        - "cluster"
        - --route-vserver-addr
        - "192.168.131.100"
      volumes:
      - name: bigip-creds
        secret:
           secretName: bigip-login
