apiVersion: cis.f5.com/v1
kind: F5BigIpCtlr
metadata:
  name: f5-server
  namespace: openshift-operators
spec:
  args:
    log_as3_response: true
    manage_routes: true
    manage_ingress: true
    manage_configmaps: true
    agent: as3
    log_level: INFO
    route_vserver_addr: 10.1.10.100
    bigip_partition: ocp
    openshift_sdn_name: /Common/openshift_vxlan
    bigip_url: 	10.1.20.240
    insecure: true
    pool-member-type: cluster
    namespace: default
    override-as3-declaration: default/f5-as3-override
  bigip_login_secret: bigip-login
  image:
    pullPolicy: IfNotPresent
    repo: k8s-bigip-ctlr
    user: f5networks
  namespace: kube-system
  rbac:
    create: true
  resources: {}
  serviceAccount:
    create: true
    name: null
  version:  2.0.0
