apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-tls
  namespace: nginx-ingress
  labels:
    cis.f5.com/as3-tenant: ConfigMap
    cis.f5.com/as3-app: MyApps
    cis.f5.com/as3-pool: ingresstls_pool
spec:
  type: NodePort
  ports:
#    - name: http
#      port: 80
#      targetPort: 80
#      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
      app: my-nginx-ingress-controller
---

