apiVersion: v1
kind: Service
metadata:
  name: my-frontend
  labels:
    app: my-frontend

spec:
  ports:
  - name: my-frontend
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-frontend
