apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-frontend
  template:
    metadata:
      labels:
        app: my-frontend
    spec:
      containers:
      - image: "f5devcentral/f5-demo-httpd:openshift"
        env:
        - name: F5DEMO_APP
          value: "website"
        - name: F5DEMO_NODENAME
          value: "CIS Route"
        imagePullPolicy: IfNotPresent
        name: my-frontend
        ports:
        - containerPort: 8080
          protocol: TCP

