apiVersion: v1
kind: Service
metadata:
  name: my-frontend3
  labels:
    run: my-frontend3
spec:
  ports:
  - name: my-frontend3
    port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort
  selector:
    run: my-frontend3
