apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-frontend2
  template:
    metadata:
      labels:
        app: my-frontend2
    spec:
      containers:
      - image: "f5devcentral/f5-demo-httpd:openshift"
        env:
        - name: F5DEMO_APP
          value: "website"
        - name: F5DEMO_NODENAME
          value: "CIS ConfigMap"
        imagePullPolicy: IfNotPresent
        name: my-frontend2
        ports:
        - containerPort: 8080
          protocol: TCP

