apiVersion: "cis.f5.com/v1"
kind: NginxCisConnector
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  virtualServerAddress: "10.1.10.102"
  iRules:
  - /Common/Proxy_Protocol_iRule
  selector:
    matchLabels:
      app: nginx-ingress-cis
