apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-green
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: node-green
    spec:
      containers:
      - image: "f5devcentral/f5-demo-httpd:openshift"
        env:
        - name: F5DEMO_APP
          value: "website"
        - name: F5DEMO_NODENAME
          value: "Node Green (No SSL)"
        - name: F5DEMO_COLOR
          value: "99FF99"
        - name: F5DEMO_NODENAME_SSL
          value: "Node Green (SSL)"
        - name: F5DEMO_COLOR_SSL
          value: "00FF00"
        imagePullPolicy: IfNotPresent
        name: node-green
        ports:
        - containerPort: 8080
        - containerPort: 8443
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: node-green
  labels:
    run: node-green
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  type: NodePort
  selector:
    run: node-green

---
apiVersion: v1
kind: Service
metadata:
  name: node-green-tls
  labels:
    run: node-green-tls
    cis.f5.com/as3-tenant: AS3
    cis.f5.com/as3-app: MyApps
    cis.f5.com/as3-pool: greentls_pool    
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
    name: https
  type: NodePort
  selector:
    run: node-green
