apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: www
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: www
    spec:
      containers:
      - image: "f5devcentral/f5-demo-httpd:openshift"
        env:
        - name: F5DEMO_APP
          value: "website"
        - name: F5DEMO_NODENAME
          value: "WWW Route"
        - name: F5DEMO_NODENAME
          value: "WWW Route (SSL Backend)"
        imagePullPolicy: IfNotPresent
        name: www
        ports:
        - containerPort: 8443
          protocol: TCP

