kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration
  namespace: default
data:
  template: |
    {
        "declaration": {
            "kubernetes_AS3": {
                "Shared": {
                    "ingress_10_1_10_82_80": {
                        "securityLogProfiles": [
                            {
                                "bigip": "/Common/Log all requests"
                            }
                        ],
                        "policyWAF": {
                            "bigip": "/Common/linux-low"
                        }
                    }
                }
            }
        }
    }
