---
# Source: f5-bigip-ctlr/templates/f5-bigip-ctlr-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bigip2-f5-bigip-ctlr
  namespace: kube-system
  labels:
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.7
    release: bigip2
    heritage: Tiller
---
# Source: f5-bigip-ctlr/templates/f5-bigip-ctlr-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: bigip2-f5-bigip-ctlr
  labels:
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.7
    release: bigip2
    heritage: Tiller
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
      - apps
      - extensions
      - route.openshift.io
    resources:
      - nodes
      - services
      - endpoints
      - namespaces
      - ingresses
      - secrets
      - pods
      - routes
  - verbs:
      - get
      - list
      - watch
      - update
      - create
      - patch
    apiGroups:
      - ''
      - apps
      - extensions
      - route.openshift.io
    resources:
      - configmaps
      - events
      - ingresses/status
      - routes/status
---
# Source: f5-bigip-ctlr/templates/f5-bigip-ctlr-clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: bigip2-f5-bigip-ctlr
  namespace: kube-system
  labels:
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.7
    release: bigip2
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bigip2-f5-bigip-ctlr
subjects:
- kind: ServiceAccount
  name: bigip2-f5-bigip-ctlr
  namespace: kube-system
---
# Source: f5-bigip-ctlr/templates/f5-bigip-ctlr-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigip2-f5-bigip-ctlr
  namespace: kube-system
  labels:
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-0.0.7
    release: bigip2
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5-bigip-ctlr
  template:
    metadata:
      labels:
        app: f5-bigip-ctlr
        release: bigip2
    spec:
      serviceAccountName: bigip2-f5-bigip-ctlr
      containers:
      - name: f5-bigip-ctlr
        image: "f5networks/k8s-bigip-ctlr:2.2.0"
        volumeMounts:
        - name: bigip-creds
          mountPath: "/tmp/creds"
          readOnly: true
        imagePullPolicy: Always
        command:
        - /app/bin/k8s-bigip-ctlr
        args:
        - --credentials-directory
        - /tmp/creds
        - --agent
        - "as3"
        - --bigip-partition
        - "kubernetes"
        - --bigip-url
        - "10.1.10.241"
        - --flannel-name
        - "flannel_vxlan"
        - --insecure
        - "true"
        - --override-as3-declaration
        - "default/f5-as3-override"
        - --pool-member-type
        - "cluster"
      volumes:
      - name: bigip-creds
        secret:
           secretName: bigip-login

