apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: f5-ingress
  annotations:
    kubernetes.io/ingress.class: "f5"
    virtual-server.f5.com/ip: "10.1.10.83"
    virtual-server.f5.com/partition: "kubernetes_AS3"
spec:
  rules:
  - host: www.f5demo.com
    http:
      paths:
      - backend:
          serviceName: my-website
          servicePort: 80
  - host: app1.f5demo.com
    http:
      paths:
      - backend:
          serviceName: app1
          servicePort: 80
